Repository oclif/plugin-plugins, pull requests merged in 2023-11, with the labels that each got.

#702 fix: HUSKY=0 on github installs
  package.json
  src/plugins.ts
  src/yarn.ts
  yarn.lock
Labels: bug

#701 feat: add plugins reset cmd
  src/commands/plugins/reset.ts
Labels: enhancement

#708 fix: allow installing legacy plugins if @oclif/plugin-legacy in plugins
  src/plugins.ts
  test/integration/install.integration.ts
Labels: cla:signed

#721 fix: scope install warnings to plugin being installed
  src/util.ts
  test/utils.test.ts
Labels: enhancement
